name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  NODE_VERSION: '24.x'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build
        run: yarn build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3.0.0
        with:
          files: |
            dist/meshtastic-chat-card.js
            dist/meshtastic-chat-card.js.gz
          generate_release_notes: true
